# this is need password auth
spring.data.mongodb.uri=mongodb://fwh:123456@localhost:27017/test

# not need auth 
#spring.data.mongodb.uri=mongodb://127.0.0.1:22222/test

# MongoDB配置
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test
spring.data.mongodb.username=fwh
spring.data.mongodb.password=123456
spring.data.mongodb.authentication-database=admin

# 连接池配置
spring.data.mongodb.min-connections-per-host=10
spring.data.mongodb.max-connections-per-host=100
spring.data.mongodb.threads-allowed-to-block-for-connection-multiplier=5
spring.data.mongodb.server-selection-timeout=30000
spring.data.mongodb.max-wait-time=120000
spring.data.mongodb.max-connection-idel-time=0
spring.data.mongodb.max-connection-life-time=0
spring.data.mongodb.connect-timeout=10000
spring.data.mongodb.socket-timeout=0